name: Release

on:
  push:
    paths:
      - 'src/**'
      - 'test/**'
      - 'Directory.Build.props'
      - '**/build.yml'
    # tags:
    #   - "*.*.*"
    branches:
      - master
  # pull_request:
  #   paths:
  #     - 'src/**'
  #     - 'test/**'
  #     - 'Directory.Build.props'
  #     - '**/build.yml'
  workflow_dispatch:

jobs:
  publish:
    name: Build and Publish NuGets
    timeout-minutes: 60
    strategy:
    # max-parallel: 2
      matrix: 
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    # if: github.ref == 'refs/heads/master' && success()
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Clean
        run: dotnet clean --configuration Release
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --configuration Release --no-restore --no-build -l trx --verbosity normal
      - name: Pack
        run: dotnet pack --no-build --configuration Release --output .
      - name: PushNuget
        run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts/**/*